import { type Metadata } from "next";
import "./globals.css";
import ClerkProviderLayout from "./ClerkProviderThemeLayout";

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body suppressHydrationWarning>
        <ClerkProviderLayout>{children}</ClerkProviderLayout>
      </body>
    </html>
  );
}
