import { type Metadata } from "next";
import { ClerkLoading, ClerkProvider, ClerkLoaded } from "@clerk/nextjs";
import "./globals.css";
import { dark, neobrutalism, shadesOfPurple } from "@clerk/themes";

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: [neobrutalism], // or shadesOfPurple, or dark like [dark, neobrutalism, shadesOfPurple]
      }}
    >
      <html suppressHydrationWarning>
        <body>
          <ClerkLoading>
            <div>
              Clerk is loading... Here add your loading spinner or animation
            </div>
          </ClerkLoading>
          <ClerkLoaded>{children}</ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}
